var annotated_dup =
[
    [ "_CanInterface", "d8/df7/struct___can_interface.html", "d8/df7/struct___can_interface" ],
    [ "_CanMailbox", "d3/d3f/struct___can_mailbox.html", "d3/d3f/struct___can_mailbox" ],
    [ "_eQEPInterface", "dc/dd4/struct__e_q_e_p_interface.html", "dc/dd4/struct__e_q_e_p_interface" ],
    [ "_I2CInterface", "d4/dfa/struct___i2_c_interface.html", "d4/dfa/struct___i2_c_interface" ],
    [ "_I2CMSG_transmit", "dc/d88/struct___i2_c_m_s_g__transmit.html", "dc/d88/struct___i2_c_m_s_g__transmit" ],
    [ "_SCIInterface", "d2/d84/struct___s_c_i_interface.html", "d2/d84/struct___s_c_i_interface" ],
    [ "_SPIInterface", "d4/dbd/struct___s_p_i_interface.html", "d4/dbd/struct___s_p_i_interface" ],
    [ "_TMS_ADC", "d4/d2c/struct___t_m_s___a_d_c.html", "d4/d2c/struct___t_m_s___a_d_c" ],
    [ "_TMS_ADC_RESULT", "d9/db3/struct___t_m_s___a_d_c___r_e_s_u_l_t.html", "d9/db3/struct___t_m_s___a_d_c___r_e_s_u_l_t" ],
    [ "_TMS_CAN", "dc/d1a/struct___t_m_s___c_a_n.html", "dc/d1a/struct___t_m_s___c_a_n" ],
    [ "_TMS_CAN_MO", "d7/d68/struct___t_m_s___c_a_n___m_o.html", "d7/d68/struct___t_m_s___c_a_n___m_o" ],
    [ "_TMS_ECAP", "d2/d38/struct___t_m_s___e_c_a_p.html", "d2/d38/struct___t_m_s___e_c_a_p" ],
    [ "_TMS_EPWM", "db/dec/struct___t_m_s___e_p_w_m.html", "db/dec/struct___t_m_s___e_p_w_m" ],
    [ "_TMS_EQEP", "d0/d4f/struct___t_m_s___e_q_e_p.html", "d0/d4f/struct___t_m_s___e_q_e_p" ],
    [ "_TMS_I2C", "da/dac/struct___t_m_s___i2_c.html", "da/dac/struct___t_m_s___i2_c" ],
    [ "_TMS_I2C_Reg", "d3/de8/struct___t_m_s___i2_c___reg.html", "d3/de8/struct___t_m_s___i2_c___reg" ],
    [ "_TMS_INT_REGS", "d3/d4b/struct___t_m_s___i_n_t___r_e_g_s.html", "d3/d4b/struct___t_m_s___i_n_t___r_e_g_s" ],
    [ "_TMS_PIE", "d5/dfd/struct___t_m_s___p_i_e.html", "d5/dfd/struct___t_m_s___p_i_e" ],
    [ "_TMS_PIE_GROUP", "d4/d89/struct___t_m_s___p_i_e___g_r_o_u_p.html", "d4/d89/struct___t_m_s___p_i_e___g_r_o_u_p" ],
    [ "_TMS_PIO", "d8/db8/struct___t_m_s___p_i_o.html", "d8/db8/struct___t_m_s___p_i_o" ],
    [ "_TMS_PIO_CTL", "d3/d0e/struct___t_m_s___p_i_o___c_t_l.html", "d3/d0e/struct___t_m_s___p_i_o___c_t_l" ],
    [ "_TMS_PIO_DATA", "dc/d90/struct___t_m_s___p_i_o___d_a_t_a.html", "dc/d90/struct___t_m_s___p_i_o___d_a_t_a" ],
    [ "_TMS_SCI", "dc/d37/struct___t_m_s___s_c_i.html", "dc/d37/struct___t_m_s___s_c_i" ],
    [ "_TMS_SCR", "d8/def/struct___t_m_s___s_c_r.html", "d8/def/struct___t_m_s___s_c_r" ],
    [ "_TMS_SPI", "dc/d6d/struct___t_m_s___s_p_i.html", "dc/d6d/struct___t_m_s___s_p_i" ],
    [ "_TMS_TIM_INT_REGS", "d7/d18/struct___t_m_s___t_i_m___i_n_t___r_e_g_s.html", "d7/d18/struct___t_m_s___t_i_m___i_n_t___r_e_g_s" ],
    [ "_TMS_TIMER", "de/dda/struct___t_m_s___t_i_m_e_r.html", "de/dda/struct___t_m_s___t_i_m_e_r" ],
    [ "_TMS_XINT", "d8/d3a/struct___t_m_s___x_i_n_t.html", "d8/d3a/struct___t_m_s___x_i_n_t" ]
];