var adc_8c =
[
    [ "Code example", "dd/dc4/system_controls.html#autotoc_md98", null ],
    [ "Documented C-Code of module:", "dd/dc4/system_controls.html#autotoc_md100", null ],
    [ "Detailed description in Technical Reference Manual:", "dd/dc4/system_controls.html#autotoc_md102", null ],
    [ "Code example", "d9/d79/general_output_pin.html#autotoc_md72", null ],
    [ "Documented C-Code of module:", "d9/d79/general_output_pin.html#autotoc_md74", null ],
    [ "Detailed description in Technical Reference Manual:", "d9/d79/general_output_pin.html#autotoc_md76", null ],
    [ "Code example", "d0/dcf/general_input_pin.html#autotoc_md66", null ],
    [ "Documented C-Code of module:", "d0/dcf/general_input_pin.html#autotoc_md68", null ],
    [ "Detailed description in Technical Reference Manual:", "d0/dcf/general_input_pin.html#autotoc_md70", null ],
    [ "Code example", "db/d69/adc.html#autotoc_md19", null ],
    [ "Documented C-Code of module:", "db/d69/adc.html#autotoc_md21", null ],
    [ "Detailed description in Technical Reference Manual:", "db/d69/adc.html#autotoc_md23", null ],
    [ "Code example", "d8/d8d/can.html#autotoc_md26", null ],
    [ "Documented C-Code of module:", "d8/d8d/can.html#autotoc_md28", null ],
    [ "Detailed description in Technical Reference Manual:", "d8/d8d/can.html#autotoc_md30", null ],
    [ "Code example", "d3/db1/cpu_timer.html#autotoc_md32", null ],
    [ "Documented C-Code of module:", "d3/db1/cpu_timer.html#autotoc_md34", null ],
    [ "Detailed description in Technical Reference Manual:", "d3/db1/cpu_timer.html#autotoc_md36", null ],
    [ "Code example 1 (Capture mode)", "db/dd5/ecap.html#autotoc_md42", null ],
    [ "Code example 2 (PWM mode)", "db/dd5/ecap.html#autotoc_md44", null ],
    [ "Documented C-Code of module:", "db/dd5/ecap.html#autotoc_md46", null ],
    [ "Detailed description in Technical Reference Manual:", "db/dd5/ecap.html#autotoc_md48", null ],
    [ "Initialisation of ePWM Pins", "d4/d15/epwm.html#autotoc_md51", null ],
    [ "Code example", "d4/d15/epwm.html#autotoc_md53", null ],
    [ "Documented C-Code of module:", "d4/d15/epwm.html#autotoc_md55", null ],
    [ "Detailed description in Technical Reference Manual:", "d4/d15/epwm.html#autotoc_md57", null ],
    [ "Code example", "d1/dc6/eqep.html#autotoc_md60", null ],
    [ "Documented C-Code of module:", "d1/dc6/eqep.html#autotoc_md62", null ],
    [ "Detailed description in Technical Reference Manual:", "d1/dc6/eqep.html#autotoc_md64", null ],
    [ "Code examples", "d8/d6b/i2c.html#autotoc_md78", null ],
    [ "Documented C-Code of module:", "d8/d6b/i2c.html#autotoc_md80", null ],
    [ "Detailed description in Technical Reference Manual:", "d8/d6b/i2c.html#autotoc_md82", null ],
    [ "Code example", "d1/d15/sci.html#autotoc_md85", null ],
    [ "Documented C-Code of module:", "d1/d15/sci.html#autotoc_md87", null ],
    [ "Detailed description in Technical Reference Manual:", "d1/d15/sci.html#autotoc_md89", null ],
    [ "Code example", "dd/dbe/spi.html#autotoc_md92", null ],
    [ "Documented C-Code of module:", "dd/dbe/spi.html#autotoc_md94", null ],
    [ "Detailed description in Technical Reference Manual:", "dd/dbe/spi.html#autotoc_md96", null ],
    [ "Code example", "df/d8b/delay.html#autotoc_md39", null ],
    [ "Error-Message description", "d6/db4/error10099.html#autotoc_md0", null ],
    [ "How to fix this error", "d6/db4/error10099.html#autotoc_md2", null ],
    [ "ADC_getValue", "de/d01/adc_8c.html#a46eed8e83cec60c30eec5428805f2ade", null ],
    [ "init_ADC", "de/d01/adc_8c.html#a342ab07b607f3dc4efa0655ca1acd164", null ]
];